[workspace]
resolver = "2"
members = [
    "crates/binas-core",
    "crates/binas-pdf",
    "crates/binas-cli",
    "bindings/binas-pdf-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license-file = "LICENSE"
repository = "https://github.com/oxhq/binas"
homepage = "https://github.com/oxhq/binas"

[workspace.dependencies]
binas-core = { path = "crates/binas-core", version = "0.1.0" }
binas-pdf = { path = "crates/binas-pdf", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
